name: build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          17
          11

    - name: build & publish (sonatype)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SIGN_KEY: ${{ secrets.SIGN_KEY }}
#        SIGN_PWD: ${{ secrets.SIGN_PWD }}
        ORG_GRADLE_PROJECT_signKey: ${{ secrets.SIGN_KEY_ORG }}
        ORG_GRADLE_PROJECT_signPwd: ${{ secrets.SIGN_PWD }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
      run: ./gradlew build publishToSonatype -s

# -i -d
