name: build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:

  check-publish:
    name: check publish
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ env.BUILD_VERSION }}
      BUILD_SNAPSHOT: ${{ env.BUILD_SNAPSHOT }}
      BUILD_PUBLISH: ${{ env.BUILD_PUBLISH }}

    steps:
      - name: get version
        id: get-version
        uses: openapi-processor/openapi-processor-base/.github/actions/version@main
        with:
          version-file: 'gradle/libs.versions.toml'
          version-path: 'versions.project'

      - name: set version outputs
        shell: bash
        run: |
          echo BUILD_VERSION="${{steps.get-version.outputs.version}}" >> $GITHUB_ENV
          echo BUILD_SNAPSHOT="${{steps.get-version.outputs.snapshot}}" >> $GITHUB_ENV
          echo BUILD_PUBLISH="${{steps.get-version.outputs.publish}}" >> $GITHUB_ENV
          cat $GITHUB_ENV

  build:
    name: build & test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17

    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_signKey: ${{ secrets.SIGN_KEY }}
        ORG_GRADLE_PROJECT_signPwd: ${{ secrets.SIGN_PWD }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
      run: ./gradlew check --stacktrace

  publish:
    needs: [check-publish, build]
    name: publish (maven central)

    runs-on: ubuntu-latest
    if: needs.check-publish.outputs.BUILD_PUBLISH == 'true'

    steps:
    - uses: actions/checkout@v6

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17

    - name: build & publish (sonatype)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_signKey: ${{ secrets.SIGN_KEY }}
        ORG_GRADLE_PROJECT_signPwd: ${{ secrets.SIGN_PWD }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
      run: ./gradlew build publishToMavenCentral --stacktrace
